# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=200, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenID',
                'ordering': ['openid'],
                'verbose_name_plural': 'OpenIDs',
            },
        ),
        migrations.CreateModel(
            name='TrustedRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_root', models.CharField(max_length=200)),
                ('openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openid_provider.OpenID')),
            ],
        ),
    ]
